### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by gingerbeardman** [Thabke/Jissen-Mahjong-controller-to-USB-converter#1]
I bought one of these controllers a year ago, just before Christmas 2019 and the pandemic, and never got around to doing anything with it... until now! I fired up the Arduino IDE, plugged in my Leonardo, and then thought to myself. I wonder if anybody has done this in the year that has passed. And... lo! You have. 

So thanks! I'll use your code now.

My goal is to play Hanafuda 🎴 games with the controller, rather than Mahjong 🀄️.

Cheers!

**Comment by Thabke** [comment]
Good luck with your project.

**Comment by gingerbeardman** [comment]
Do you have a photos of your controller?

I'd like to see how you did the wiring. 

Thanks!

**Comment by Thabke** [comment]
Because of covid, I'm kind of stuck in a place far from this controller.  I'm sorry.

**Comment by gingerbeardman** [comment]
Take care, stay safe!

I'll figure it out and post a photo of my work.

**Comment by gingerbeardman** [comment]
Here we go! Thanks again for your Arduino code. 

![A556ED5F-9E5A-49A4-A34E-5E79CB6636E9](https://user-images.githubusercontent.com/49612/104108764-37015f00-52bf-11eb-8fd1-ec779bb92e28.jpeg)
